// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Projekat.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20220321215125_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DokumentDrzava", b =>
                {
                    b.Property<int>("PodrzaneDrzaveID")
                        .HasColumnType("int");

                    b.Property<int>("PodrzaniDokumentiID")
                        .HasColumnType("int");

                    b.HasKey("PodrzaneDrzaveID", "PodrzaniDokumentiID");

                    b.HasIndex("PodrzaniDokumentiID");

                    b.ToTable("DokumentDrzava");
                });

            modelBuilder.Entity("DrzavaPoternica", b =>
                {
                    b.Property<int>("TrazeniLjudiID")
                        .HasColumnType("int");

                    b.Property<int>("ZabranjenUlazUDrzaveID")
                        .HasColumnType("int");

                    b.HasKey("TrazeniLjudiID", "ZabranjenUlazUDrzaveID");

                    b.HasIndex("ZabranjenUlazUDrzaveID");

                    b.ToTable("DrzavaPoternica");
                });

            modelBuilder.Entity("Models.Dokument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("Drzavljanstvo")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Dokument");
                });

            modelBuilder.Entity("Models.Drzava", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("Drzava");
                });

            modelBuilder.Entity("Models.Poternica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stroga")
                        .HasMaxLength(50)
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Poternica");
                });

            modelBuilder.Entity("DokumentDrzava", b =>
                {
                    b.HasOne("Models.Drzava", null)
                        .WithMany()
                        .HasForeignKey("PodrzaneDrzaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Dokument", null)
                        .WithMany()
                        .HasForeignKey("PodrzaniDokumentiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrzavaPoternica", b =>
                {
                    b.HasOne("Models.Poternica", null)
                        .WithMany()
                        .HasForeignKey("TrazeniLjudiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Drzava", null)
                        .WithMany()
                        .HasForeignKey("ZabranjenUlazUDrzaveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
